### PR TITLE
Add support for Nsis version 3.08.

### PR DESCRIPTION
**Pull request by mboulom**
Don't really know what I am doing.
Need Nsis version 3.08 for added support for !uninstfinalize
Please help.

### CODE REVIEW

**Comment by JacobIpsen** [comment]
Plan for Commit ?

**Comment by mboulom** [comment]
Committing 🤞

**Review by mboulom — COMMENTED** [review]
Please review ? Not planning any additional changes.

**Review by JacobIpsen — APPROVED** [review]
All looks fine, the zip contains the correct version, in the same structure as orginal :)

**Review by JacobIpsen — COMMENTED** [review]
Not shure this will work, just tryed deployinf the zip to our production env.
and seems like the path needs to be changed for the nsis-3.08 to work 

Not shure but think it is in the ps1 file

**Comment by development-bizeta-mestre** [comment]
We will look into it this week. This will most likely be in a `version 3` of the task to ensure we don't break existing pipelines..

**Comment by JacobIpsen** [comment]
> We will look into it this week. This will most likely be in a `version 3` of the task to ensure we don't break existing pipelines..

Super cool, if u need help testing i am glad to lend a hand :)

**Comment by development-bizeta-mestre** [comment]
@JacobIpsen I've merged and released the new **version 3.0.0** of the task (ps: don't forget to change version 3 on your yaml pipeline) . 

I don't have the path issue you mentioned, but I do have something else that doesn't seem to work well. I'll investigate further tomorrow. In the meantime give it a spin and let me know what you think.

**Comment by development-bizeta-mestre** [comment]
Ok the arguments are passed ok now ( This is related to the issue #18 )

**Pull request merged**
